jenkins-plugin: add retry layer/adapter for REST invocations
openshift/jenkins-plugin pull request #141
Opened 2017-05-24 20:40 UTC by gabemontero

Bug 1454485
    Bugzilla link https://bugzilla.redhat.com/show_bug.cgi?id=1454485
    Detailed explanation
    Implement a general retry mechanism for failing HTTP REST operations
    against the OpenShift master

@bparees @oatmealraisin FYI

2017-05-24 21:03 UTC, bparees requested changes

2017-05-24 21:03 UTC, bparees commented on src/main/java/com/openshift/jenkins/plugins/pipeline/MessageConstants.java
> +public static final String RETRY = "\nA execption occurred invoking a REST operation against the OpenShift master.  The operation will be retried.  Exception message \"%s\".";
exception.

2017-05-24 21:03 UTC, bparees commented on src/main/java/com/openshift/jenkins/plugins/pipeline/model/RetryIClient.java
> +            }
needs a return if we didn't catch an exception?

2017-05-24 21:03 UTC, bparees commented on src/main/java/com/openshift/jenkins/plugins/pipeline/model/RetryIClient.java
> +                return o;
I assume standard failures like "permission denied" or "unknown resource" do not result in exceptions from call()?

2017-05-25 00:50 UTC, gabemontero commented on src/main/java/com/openshift/jenkins/plugins/pipeline/model/RetryIClient.java
> +            }
damn i had that in there at one time .... I was messing with `Void` vs. `void` and must have forgot to put it back ... that resulted in the test failure too.   Thanks for the catch.

2017-05-25 00:54 UTC, gabemontero commented on src/main/java/com/openshift/jenkins/plugins/pipeline/model/RetryIClient.java
> +                return o;
Another good catch ... turns out restclient has `UnauthorizedException`, `NotFoundException`, and `BadRequestException` (rc's 403, 404, and 400).  I'll check for those and *NOT* retry.

2017-05-25 03:26 UTC, gabemontero commented
Ah ... the httpGet path needs some work

2017-05-25 20:33 UTC, gabemontero commented
ok tests are clean now with some more tweaks to the error handling .. have 1 more mod I'm about to try

2017-05-26 13:55 UTC, gabemontero commented
interesting ... a concurrent mod in this run uncovered a NPE ... will address NPE, and investigate if there is a deeper issue wrt retry

2017-05-26 14:00 UTC, gabemontero commented
ah yes ... the master sends back an HTTP rc 409, which the restclient does not deal with specifically ... we already had retry for this higher up the plugin stack

IMO simply addressing the NPE in the new logic is sufficient  ... will push momentarily

2017-05-26 18:03 UTC, gabemontero commented
OK ... tests are looking good.

@bparees - any more suggestions before merging?

2017-05-26 19:31 UTC, bparees commented
lgtm

2017-05-26 19:36 UTC, merged